### ISSUE TITLE
TODO + TODO by baksIII

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2597]
- [x] Тогда для тайтлов 0.71, а для персов\людишек 0.642 (по старому).
- [x] При наведении на постер отображается размер и есть небольшое засветление. Лучше все это убрать, оставив только курсор-лупу (курсора вполне хватит).
- [ ] при открытии страницы постер на долю секунды "прыгает".
- [x] render poster preview image
- [x] (?). Смещение. Оно вряд ли связано с размытием. Выглядит так будто это из-за не кратного количества пикселей и браузер "наугад" выберает куда сместится.
- [x] Зашакалевание оригинала постера при многократном редактировании.
- [x] https://shikimori.one/characters/210576-sumire-s-sister
Сломалось редактирование из-за новых постеров.
При нажатии "шестеренки" выдает ошибку 500.
- [x] Все загруженые ранее постеры самоликведировались.
- [x] Хранение имени постера и синхронизация с его использованием.
- [x] Перед заменой старой системы на новую, удалить все тестовые постеры, связаные с ними правки и "poster" из "не синхронизировать".
- [x] После 9 пункта заменить  image на poster в "не синхронизировать". Иначе везде где не нужно синхронизация восстановится.
- [ ] После ввода в эксплуатацию новой системы постеров спарсить все постеры с Мал независимо от имени файла (чтобы даже неизменные постеры обновились).
