### ISSUE TITLE
todo by baksIII v3

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2620]
- [x] poster removal must remove "poster" from desynced
- [x] Вот у таких людей, во всплывающем окне, отображаются "лучшие работы" (которых нет), а не "лучшие роли".
https://shikimori.one/people/43823-eudes-carvalho
https://shikimori.one/people/44841-leonardo-jos
Видимо это потому что сайт их как сейю не рапознает?

- [x] https://shikimori.one/comments/9176491 аниме/манга в тултипах на страницах персонажей ломается из-за этого [правила](https://github.com/shikimori/shikimori/blob/master/app/assets/stylesheets/pages/p-characters.sass#L30):
![img](https://agileseason3.s3.eu-central-1.amazonaws.com/cb84dfb4fab317a4812de8fa788e47d5.png)

- [x] В болке "новости", напортив "Вышел N эпизод" указываться же местное, а не московское?

- [x] "Приглашения в клуб сломались? Одному человеку его можно бесконечное количество раз отправить, хотя раньше появлялось сообщение о том что его уже приглашали. Приглашение можно отправить даже если ничего не вводить в поле. Я даже сам себе его смог отправить, хотя никакого уведомления после этого и не получил"  - **won't fix. все работает ка к должно**

- [x] https://myanimelist.net/anime/52381
На МАЛ изменили систему ссылок (разбили на несколько пунктов), так что они не парсятся.
- [x] https://shikimori.one/moderations/versions/1109465 "Это не единичный случай. Ссылки на Kage Project подгружены с Anime 365. Для таких вот тайтлов, где нет никакого перевода, они ведут на Акиру. Это пережиток старых времён или фича до сих пор активна?"
С Anime 365 до сих пор притягиваются ссылки? Если да, то вероятно лучше откл. Если нет, то можно ли их как-то отловить? Чтобы проверить или снести.

- [x] Можно как-то изменить систему ссылок, которые подгружаются с MALа? В том плане, чтобы они отображались при редактировании?
https://shikimori.one/animes/53613-dead-mount-death-play/edit/external_links
https://shikimori.one/moderations/versions/1117860

- [x] Удаление подгруженных ссылок более простым и быстрым способом чем через NONE. Сейчас это доставляет особый геморрой, так как куча постоянно добавляемых китайских тайтлов несёт с собой битые или не верные ссылки (поэтому 90% ссылок у них приходится отключать и исправлять).

- [x] Сделать выборку страниц, в описаниях которых скобки идут сразу после текста. Чтобы поправить их вручную.

- [x] https://shikimori.one/comments/9125783 спойлер перекрывает сэйю.

- [x] https://shikimori.one/mangas/20389-alice
Почему-то не разрывается связь с персонажами и автором (на Мал связи нет).

- [x] Периодически не приходят уведомления.
https://shikimori.one/morr/messages/news
(например об анонсах этих тайтлов
https://shikimori.one/animes/54234-suki-na-ko-ga-megane-wo-wasureta
https://shikimori.one/animes/54112-zom-100-zombie-ni-naru-made-ni-shitai-100-no-koto)

- [x] https://shikimori.one/comments/9101096
Окончание ошибочно отталкивается от пола модератора, а не пользователя.

- [x] Сделать отображение всех аниме, у которых какое-то поле desynced - на странице аниме desynced поля теперь отображены ссылками на каталог с фильтром по этому полю

- [x] #2649 - отложено
https://shikimori.one/morr/history

- [x] Тут все еще фулл отображается (людям/персам, в отличии от тайтлов, в принципе везде кроме основной страницы нужно привюшку отображать, либов результатах поиска отображать по тому же принципу что и тайтлы)
https://shikimori.one/people?search=Hiroyasu%20Kobayashi

- [x] Создать список постеров загруженных вручную с 15-20 декабря (с ввода системы) по примерно 10 января.

- [x] Постеры все же битые просачиваются.
https://shikimori.one/mangas/147088-who-can-define-popularity
https://shikimori.one/mangas/147202-my-s-class-hunters
https://shikimori.one/mangas/152743-please-kill-my-husband
https://shikimori.one/mangas/146385-the-divine-twilight-s-return
https://shikimori.one/mangas/70941-domestic-na-kanojo

- [x] Переместить постеры с SSD на HDD - слишком много места они стали занимать

- [x] https://shikimori.one/animes/51125-inamori-asuto-no-soccer-kyoushitsu/edit/poster
https://shikimori.one/animes/51375-hakkoutai-solar-cycle/edit/poster
При редактировании постера который, из-за ширины, отображается в поиске фулл, область кропа показывается по умолчанию (хотя на деле выбран крайний левый угол).
Вот, из связанного тайтла это видно.
https://shikimori.one/animes/33733-inazuma-eleven-ares-no-tenbin
https://shikimori.one/animes/44042-holo-no-graffiti
![img](https://agileseason3.s3.eu-central-1.amazonaws.com/629aa9969b0b3d6109dc23bb61c8a4ba.jpg)
Upd: с телефона все нормально отображается. С ПК нет.
![img](https://agileseason3.s3.eu-central-1.amazonaws.com/7e1f3821393fe8545cddb4ab468b2705.jpg)

- [x] https://shikimori.one/moderations/versions/1155633
И в правках не видна область кропа широких постеров.

- [x] https://shikimori.one/moderations/versions/content - wont fix
Возможность выбрать больше одного "поля" в фильтре.

- [x] https://shikimori.one/comments/9220793
- [x] Сделать кроп персов\людей нельзя было сделать меньше 225 по ширине или 350 по высоте. https://shikimori.one/moderations/versions/1166604
- [x] Manga list status icon issue
![image](https://user-images.githubusercontent.com/134610/219333629-0915c35b-0181-4373-aac3-01b3968c50e1.png) ![image](https://user-images.githubusercontent.com/134610/219333659-74164a80-1889-4041-8c4e-6b25de49880e.png)
- [x] У тайтла не видны оценки взаимных друзей, даже когда список друга "доступен только друзьям
- [x] Баг с расширенным избранным, вертикально на мобилках
https://shikimori.one/comments/9277954
- [x] https://shikimori.one/characters/199052-chao-chen/edit/poster
https://shikimori.one/characters/199053-yi-zhou/edit/poster
https://shikimori.one/characters/202829-tong-wei/edit/poster
(Это примеры, сегодняшние постеры все такие)
Потеря пикселя с каждой стороны у кропа. По крайней мере при редактировании так отображаются числовые значения.
Ручное исправление не помогает.

https://shikimori.one/moderations/versions/1174984
При этом в правке кроп отображается так, как это происходит без изменения размеров (то есть это визуальный баг страницы редактирования).
- [x] #2657
- [x] В правках video и videos в одно поле объединить.
- [x] #2651
- [x] #2607 
"Сделать кроп персов\людей нельзя было сделать меньше 225 по ширине или 350 по высоте"
- [x] На странице редактирования "английского названия" (в истории правок) начали отображаются правки из раздела "видео": https://shikimori.one/comments/9297613
- [x] 500 если попытаться сохранить описание клуба содержащее ссылку https://garugaku.com/
https://shikimori.one/comments/9322260
- [x] парсить namu.wiki ссылки с MAL
