### ISSUE TITLE
todo by baksIII and others v4

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2689]
- [x] Значек поиска перекрывает поле ввода https://shikimori.me/comments/9581640
- [x] https://shikimori.me/characters/173931-aliza
https://shikimori.me/characters/173742-doctor-heartless
Персы потеряли свои постеры ещё в декабре/январе и не парсят новые.
- [ ] Тут ещё какой-то баг с клавиатурой
![img](https://agileseason3.s3.eu-central-1.amazonaws.com/f32c31c30b782b5e0c2071ca8d72e8a6.jpg)
- [x] Растянутые изображения https://shikimori.me/comments/9611635
- [x] "защита емайлов от парсинга" https://shikimori.me/comments/9610084
- [x] проблемы в стилях https://shikimori.me/comments/9612447
- [x] видны топики закрытых клубов https://shikimori.me/comments/9525586
- [x] Проблемы банхаммера
1. Не банится вообще
еб твою мать
еп твою мать
2. Банится только часть (которая и так должна банится, поскольку является отдельной записью)
на хер
на хуй
на хуя
не ебет
по хер
по хуй
по хую

- [x] https://shikimori.me/moderations/genre_v2s/52-Seinen/edit
Вот тут название "Типа" жанра с Возраст заменить на Аудитория.
(Одно слово в коде заменить)

- [x] Что-то с удалением коллекций
https://shikimori.me/comments/9938005
https://shikimori.me/comments/9938774

- [x] https://shikimori.me/moderations/studios
Чекбокс "студия" числится устаревшим и изменить его нельзя, но на деле до сих пор работает (чем ломает отображение студий на страницах тайтлов).

- [x] У манги/ранобэ с мал парсятся ссылки на твиттер, но на самом Шики такую ссылку добавить нельзя. 
Можешь реализовать манге/ранобэ возможность добавлять ссылки на твиттер?
