### ISSUE TITLE
todo by baks v5

### ISSUE THREAD

**Issue by morr** [shikimori/shikimori#2772]
- [x] в сафари у ачивок уехали рамки
- [x] https://shikimori.one/comments/10459057
mangahub.ru переехал на .me Уж не знаю, целиком или нет.

- [x] Пачка багов жанров.
https://shikimori.one/comments/10452246
- [x] Пользователи редактируют жанры.
https://shikimori.one/moderations/versions/1333109
- [x] Не парсятся аудитории, если у тайтла более одной.

- [x] Обрезаются англ названия начиная с символа "<".

- [x] Плашка 18+ у хентая не ставится автоматически.
https://shikimori.one/animes/58185-midareuchi
https://shikimori.one/mangas/156688-minna-mesu-ni-naru
А тут не обновляется:
https://shikimori.one/animes/39731-na-bbeun-sang-sa
https://shikimori.one/animes/3565-u-jin-brand
Хотя вот тут уже всё в порядке:
https://shikimori.one/animes/58148-kemonokko-tsuushin-the-animation-tori-musume-rupia
